version: '3'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: review
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: 'var/lib/postgresql/data/pgdata'
    volumes:
      - .:./var/lib/posgresql/data

