# Generated by Django 4.0.5 on 2022-06-11 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('arrive', models.DateTimeField(default=datetime.datetime(2022, 6, 11, 10, 4, 2, 635538, tzinfo=utc))),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('unit', models.CharField(choices=[('peace', 'штук'), ('pack', 'упаковка'), ('kg', 'кг')], max_length=30, verbose_name='Единица измерения')),
                ('supplier', models.CharField(max_length=50, verbose_name='Поставщик')),
            ],
        ),
    ]
